city_to_state_dict = {
    "California": [
        "East Rancho Dominguez",
        "Moreno Valley",
        "North Glendale",
        "Santee",
        "Silver Lake",
        "Ridgecrest",
        "El Cajon",
        "Santa Maria",
        "Elk Grove",
        "Garden Grove",
        "Upland",
        "Porterville",
        "Santa Clara",
        "Woodland",
        "Goleta",
        "Agoura",
        "Huntington Beach",
        "Bellflower",
        "Eureka",
        "Escondido",
        "Santa Clarita",
        "Mead Valley",
        "Blythe",
        "Madera",
        "Oxnard Shores",
        "Monterey Park",
        "San Francisco",
        "Avocado Heights",
        "Florin",
        "Rio Linda",
        "Fremont",
        "Calexico",
        "Barstow",
        "South Whittier",
        "Castaic",
        "San Jose",
        "Oroville",
        "Rohnert Park",
        "Arroyo Grande",
        "Morgan Hill",
        "Lomita",
        "Casa de Oro-Mount Helix",
        "Vineyard",
        "Downey",
        "Fountain Valley",
        "Sherman Oaks",
        "Aliso Viejo",
        "Fallbrook",
        "Palm Desert",
        "Mountain View",
        "South Lake Tahoe",
        "Hacienda Heights",
        "Sunnyvale",
        "Foster City",
        "Baldwin Park",
        "Chowchilla",
        "Ceres",
        "San Dimas",
        "Northridge",
        "National City",
        "Tulare",
        "Castro Valley",
        "Roseville",
        "Calabasas",
        "Susanville",
        "Patterson",
        "Antelope",
        "Chico",
        "Pacific Grove",
        "Wasco",
        "Glendale",
        "Rancho Cordova",
        "Hesperia",
        "North Highlands",
        "Brea",
        "Avenal",
        "Selma",
        "Rancho Mirage",
        "San Marcos",
        "Stockton",
        "Corona",
        "Seaside",
        "Hemet",
        "Chino",
        "Paramount",
        "Sanger",
        "Daly City",
        "Culver City",
        "Rosemont",
        "Banning",
        "San Lorenzo",
        "Diamond Bar",
        "Canoga Park",
        "San Pablo",
        "Menlo Park",
        "San Rafael",
        "Clovis",
        "Los Banos",
        "Coachella",
        "Mission Viejo",
        "Rancho Palos Verdes",
        "Alameda",
        "Menifee",
        "Tracy",
        "Coronado",
        "West Covina",
        "Dinuba",
        "Oxnard",
        "West Hills",
        "Orinda",
        "San Carlos",
        "Tustin",
        "Claremont",
        "Orcutt",
        "San Leandro",
        "Palmdale",
        "Cathedral City",
        "Oildale",
        "San Bruno",
        "Antioch",
        "Santa Ana",
        "South Yuba City",
        "El Segundo",
        "Arcata",
        "Folsom",
        "Placentia",
        "Davis",
        "Prunedale",
        "Manhattan Beach",
        "Soledad",
        "Truckee",
        "Arcadia",
        "San Ramon",
        "Santa Cruz",
        "Reedley",
        "South San Francisco",
        "Simi Valley",
        "Moorpark",
        "Palm Springs",
        "Ontario",
        "Imperial Beach",
        "Pico Rivera",
        "Cameron Park",
        "Lompoc",
        "Martinez",
        "Suisun",
        "Lynwood",
        "Redding",
        "Glen Avon",
        "West Whittier-Los Nietos",
        "Paradise",
        "Petaluma",
        "Brawley",
        "Rosemead",
        "Millbrae",
        "North Hollywood",
        "Brentwood",
        "Hollister",
        "Pleasant Hill",
        "East Hemet",
        "Dublin",
        "Rancho Cucamonga",
        "Monrovia",
        "Hanford",
        "Shafter",
        "San Fernando",
        "Moraga",
        "Cupertino",
        "American Canyon",
        "Poway",
        "Huntington Park",
        "Walnut Park",
        "Salinas",
        "Redwood City",
        "Glendora",
        "Long Beach",
        "Whittier",
        "San Pedro",
        "Santa Rosa",
        "Pinole",
        "Pasadena",
        "Carmichael",
        "Florence-Graham",
        "Fullerton",
        "Citrus Heights",
        "Fair Oaks",
        "South Gate",
        "Artesia",
        "Rubidoux",
        "Woodland Hills",
        "San Mateo",
        "East Palo Alto",
        "Orangevale",
        "South Pasadena",
        "San Juan Capistrano",
        "Pleasanton",
        "Wildomar",
        "Beverly Hills",
        "Redondo Beach",
        "Agoura Hills",
        "Stanton",
        "Bay Point",
        "Compton",
        "Santa Barbara",
        "Winter Gardens",
        "Carson",
        "Ukiah",
        "Watsonville",
        "Manteca",
        "Thousand Oaks",
        "Rancho Santa Margarita",
        "Palo Alto",
        "Clearlake",
        "Napa",
        "Rocklin",
        "Irvine",
        "Redlands",
        "Twentynine Palms",
        "Los Angeles",
        "San Luis Obispo",
        "El Dorado Hills",
        "Pomona",
        "Yucca Valley",
        "Boyle Heights",
        "Chino Hills",
        "Costa Mesa",
        "Colton",
        "Berkeley",
        "Barstow Heights",
        "Rialto",
        "Willowbrook",
        "El Monte",
        "Santa Paula",
        "Adelanto",
        "Montebello",
        "Dana Point",
        "Monterey",
        "Chula Vista",
        "Pacifica",
        "Fillmore",
        "Buena Park",
        "Yorba Linda",
        "Rancho San Diego",
        "Burlingame",
        "Port Hueneme",
        "West Hollywood",
        "Arden-Arcade",
        "Azusa",
        "Fontana",
        "Bayside",
        "Atascadero",
        "Seal Beach",
        "East Los Angeles",
        "Cypress",
        "Ramona",
        "Altadena",
        "West Sacramento",
        "Arvin",
        "North Tustin",
        "Turlock",
        "Modesto",
        "Gilroy",
        "Norwalk",
        "West Puente Valley",
        "San Jacinto",
        "Torrance",
        "Yucaipa",
        "Chatsworth",
        "Santa Monica",
        "Hawthorne",
        "Gardena",
        "Paso Robles",
        "Hermosa Beach",
        "Indio",
        "Riverbank",
        "Sacramento",
        "Merced",
        "Oakland",
        "Mira Loma",
        "San Clemente",
        "Marina",
        "Milpitas",
        "El Centro",
        "Norco",
        "Cerritos",
        "Temecula",
        "Camarillo",
        "Loma Linda",
        "Echo Park",
        "La Crescenta-Montrose",
        "Rowland Heights",
        "Los Altos",
        "South San Jose Hills",
        "Alum Rock",
        "San Gabriel",
        "Yuba City",
        "Murrieta",
        "Newport Beach",
        "Westmont",
        "Covina",
        "Perris",
        "Foothill Farms",
        "Corcoran",
        "McKinleyville",
        "Bell",
        "Duarte",
        "Inglewood",
        "San Diego",
        "Granite Bay",
        "Oakley",
        "Rosamond",
        "South El Monte",
        "Desert Hot Springs",
        "Bell Gardens",
        "Atwater",
        "Anaheim",
        "Bostonia",
        "Hayward",
        "Bakersfield",
        "Nipomo",
        "Temple City",
        "Alhambra",
        "Santa Fe Springs",
        "Benicia",
        "Universal City",
        "Hercules",
        "Saratoga",
        "Delano",
        "Novato",
        "Campbell",
        "West Carson",
        "San Bernardino",
        "Encinitas",
        "Los Gatos",
        "Galt",
        "El Cerrito"
    ],
    "Mississippi": [
        "Clinton",
        "Brandon",
        "Vicksburg",
        "Hattiesburg",
        "West Gulfport",
        "Olive Branch",
        "Laurel",
        "Ridgeland",
        "Clarksdale",
        "Southaven",
        "Biloxi",
        "Horn Lake",
        "Gulfport",
        "Pearl",
        "Natchez",
        "Ocean Springs",
        "Starkville",
        "Oxford",
        "Gautier",
        "Tupelo",
        "Pascagoula"
    ],
    "New York": [
        "Nanuet",
        "Mamaroneck",
        "Bensonhurst",
        "Bellmore",
        "Cohoes",
        "Kingston",
        "Syracuse",
        "Smithtown",
        "East New York",
        "Borough of Queens",
        "Port Washington",
        "Gloversville",
        "Wantagh",
        "Staten Island",
        "Levittown",
        "Huntington",
        "Irondequoit",
        "West Babylon",
        "East Patchogue",
        "New Rochelle",
        "Centereach",
        "Pearl River",
        "Rochester",
        "Hauppauge",
        "Manhattan",
        "Roosevelt",
        "Huntington Station",
        "Peekskill",
        "New York City",
        "North Bellmore",
        "Valley Stream",
        "Westbury",
        "Selden",
        "Mineola",
        "Copiague",
        "North Tonawanda",
        "Spring Valley",
        "Lynbrook",
        "Eggertsville",
        "North Babylon",
        "Holtsville",
        "Garden City",
        "Jamestown",
        "Merrick",
        "Mount Vernon",
        "Syosset",
        "East Setauket",
        "Lindenhurst",
        "Dix Hills",
        "Rotterdam",
        "Saratoga Springs",
        "Harrison",
        "Rockville Centre",
        "Central Islip",
        "Mastic",
        "Newburgh",
        "Massapequa Park",
        "North Bay Shore",
        "White Plains",
        "Depew",
        "Lockport",
        "Glen Cove",
        "Beacon",
        "Holbrook",
        "Brooklyn",
        "Cheektowaga",
        "Oswego",
        "Monsey",
        "Sayville",
        "Elmont",
        "Scarsdale",
        "Shirley",
        "East Meadow",
        "North Amityville",
        "Kiryas Joel",
        "Plattsburgh",
        "Floral Park",
        "Greenburgh",
        "Binghamton",
        "Amsterdam",
        "Schenectady",
        "Jamaica",
        "West Albany",
        "North Valley Stream",
        "Utica",
        "Seaford",
        "Setauket-East Setauket",
        "Commack",
        "East Massapequa",
        "Franklin Square",
        "North Massapequa",
        "Lake Ronkonkoma",
        "Coney Island",
        "Melville",
        "Farmingville",
        "Uniondale",
        "Eastchester",
        "Ithaca",
        "Hempstead",
        "Bethpage",
        "Baldwin",
        "Massapequa",
        "Bay Shore",
        "Freeport",
        "Tonawanda",
        "Poughkeepsie",
        "Lackawanna",
        "Woodmere",
        "Niagara Falls",
        "Albany",
        "Islip",
        "The Bronx",
        "Cortland",
        "West Islip",
        "Rye",
        "West Seneca",
        "Long Island City",
        "Yonkers",
        "Deer Park",
        "Elmira",
        "Kings Park",
        "East Northport",
        "Amherst",
        "Ronkonkoma",
        "Coram",
        "Ossining",
        "Port Chester",
        "New City",
        "West Hempstead",
        "Hicksville",
        "Oceanside"
    ],
    "Oklahoma": [
        "Sand Springs",
        "Shawnee",
        "Chickasha",
        "Mustang",
        "Oklahoma City",
        "Tahlequah",
        "McAlester",
        "Lawton",
        "Altus",
        "Ponca City",
        "Claremore",
        "Del City",
        "Tulsa",
        "Bartlesville",
        "Muskogee",
        "Broken Arrow",
        "Ada",
        "Jenks",
        "Owasso",
        "Moore",
        "Ardmore",
        "Midwest City",
        "Stillwater",
        "Bixby",
        "Enid",
        "Sapulpa",
        "El Reno",
        "Norman",
        "Edmond",
        "Duncan",
        "Yukon",
        "Bethany",
        "Durant"
    ],
    "Maryland": [
        "Middle River",
        "Hagerstown",
        "White Oak",
        "West Elkridge",
        "Eldersburg",
        "Rockville",
        "Ellicott City",
        "Crofton",
        "Bethesda",
        "Ilchester",
        "North Bethesda",
        "Calverton",
        "Severn",
        "Owings Mills",
        "Fairland",
        "Bel Air South",
        "Camp Springs",
        "Reisterstown",
        "Dundalk",
        "Olney",
        "Glen Burnie",
        "Cockeysville",
        "Arbutus",
        "Parole",
        "Perry Hall",
        "Randallstown",
        "Wheaton",
        "Redland",
        "Severna Park",
        "Catonsville",
        "Essex",
        "Elkton",
        "Annapolis",
        "Oxon Hill",
        "Damascus",
        "South Bel Air",
        "Suitland",
        "Langley Park",
        "Silver Spring",
        "Columbia",
        "Lochearn",
        "East Riverdale",
        "Westminster",
        "Elkridge",
        "Frederick",
        "Bel Air North",
        "Potomac",
        "Greenbelt",
        "Green Haven",
        "Chillum",
        "Adelphi",
        "Salisbury",
        "Maryland City",
        "Milford Mill",
        "South Laurel",
        "Baltimore",
        "Waldorf",
        "Woodlawn",
        "North Bel Air",
        "Takoma Park",
        "Gaithersburg",
        "Glassmanor",
        "Rosedale",
        "Lake Shore",
        "Landover",
        "Hyattsville",
        "Odenton",
        "College Park",
        "Hillcrest Heights",
        "Carney",
        "Cumberland",
        "North Potomac",
        "Montgomery Village",
        "Cloverly",
        "Edgewood",
        "Rossville",
        "Pikesville",
        "Parkville",
        "Fort Washington",
        "Beltsville",
        "Ballenger Creek",
        "Seabrook",
        "Hunt Valley",
        "Bowie",
        "Towson",
        "Aspen Hill"
    ],
    "Illinois": [
        "Carbondale",
        "Naperville",
        "Champaign",
        "Rock Island",
        "Godfrey",
        "Vernon Hills",
        "Orland Park",
        "Huntley",
        "Berwyn",
        "Elgin",
        "South Elgin",
        "Bensenville",
        "Crest Hill",
        "Evanston",
        "Villa Park",
        "Urbana",
        "Skokie",
        "Cary",
        "Fairview Heights",
        "Lombard",
        "Chicago",
        "Belvidere",
        "Geneva",
        "South Holland",
        "Goodings Grove",
        "La Grange",
        "Calumet City",
        "Hoffman Estates",
        "Palatine",
        "Carol Stream",
        "O'Fallon",
        "Pekin",
        "Lake Forest",
        "Melrose Park",
        "Schaumburg",
        "East Saint Louis",
        "Sterling",
        "Park Forest",
        "Homer Glen",
        "Matteson",
        "Blue Island",
        "Dolton",
        "Shorewood",
        "Cahokia",
        "Ottawa",
        "Des Plaines",
        "Algonquin",
        "Carpentersville",
        "Addison",
        "North Aurora",
        "Plainfield",
        "Lake in the Hills",
        "Oak Lawn",
        "Franklin Park",
        "Morton Grove",
        "Machesney Park",
        "Libertyville",
        "Gurnee",
        "Northbrook",
        "Glenview",
        "Galesburg",
        "Edwardsville",
        "Evergreen Park",
        "Maywood",
        "Loves Park",
        "Woodridge",
        "Highland Park",
        "Bolingbrook",
        "Park Ridge",
        "Tinley Park",
        "Kankakee",
        "North Peoria",
        "Mundelein",
        "Lisle",
        "Buffalo Grove",
        "Roselle",
        "Hinsdale",
        "Bartlett",
        "Sycamore",
        "Hanover Park",
        "Lemont",
        "Rockford",
        "Rolling Meadows",
        "Mattoon",
        "Upper Alton",
        "Alton",
        "Romeoville",
        "North Chicago",
        "Belleville",
        "Zion",
        "Yorkville",
        "Elmhurst",
        "Prospect Heights",
        "Alsip",
        "Joliet",
        "Arlington Heights",
        "Bellwood",
        "Glen Ellyn",
        "Bridgeview",
        "Darien",
        "Grayslake",
        "West Chicago",
        "Round Lake",
        "Granite City",
        "East Moline",
        "East Peoria",
        "Bourbonnais",
        "Batavia",
        "Dixon",
        "Bradley",
        "Elk Grove Village",
        "Crystal Lake",
        "Deerfield",
        "Oak Forest",
        "DeKalb",
        "Chicago Heights",
        "Wilmette",
        "Downers Grove",
        "Country Club Hills",
        "Elmwood Park",
        "Normal",
        "Mount Prospect",
        "Mokena",
        "Woodstock",
        "Macomb",
        "Round Lake Beach",
        "Collinsville",
        "Moline",
        "Lake Zurich",
        "Washington",
        "Morton",
        "Waukegan",
        "Danville",
        "Burbank",
        "Palos Hills",
        "McHenry",
        "Cicero",
        "New Lenox",
        "Streamwood"
    ],
    "Idaho": [
        "Boise",
        "Caldwell",
        "Lewiston Orchards",
        "Kuna",
        "Post Falls",
        "Rexburg",
        "Nampa",
        "Eagle",
        "Meridian",
        "Coeur d'Alene",
        "Twin Falls",
        "Idaho Falls",
        "Moscow",
        "Pocatello"
    ],
    "Nevada": [
        "Las Vegas",
        "Sun Valley",
        "Boulder City",
        "Spanish Springs",
        "Pahrump",
        "Fernley",
        "Elko",
        "Carson City",
        "Whitney",
        "Sparks",
        "North Las Vegas",
        "Summerlin South",
        "Enterprise",
        "Reno",
        "Mesquite",
        "Sunrise Manor"
    ],
    "Colorado": [
        "Denver",
        "Commerce City",
        "Southglenn",
        "Highlands Ranch",
        "Golden",
        "Greeley",
        "Brighton",
        "Parker",
        "Loveland",
        "Littleton",
        "Fountain",
        "Windsor",
        "Broomfield",
        "Cimarron Hills",
        "Louisville",
        "Longmont",
        "Canon City",
        "Grand Junction",
        "Montrose",
        "Castle Rock",
        "Wheat Ridge",
        "Boulder",
        "Pueblo",
        "Arvada",
        "Erie",
        "Sherrelwood",
        "Colorado Springs",
        "Castlewood",
        "Durango",
        "Centennial",
        "Columbine",
        "Security-Widefield",
        "Pueblo West",
        "Ken Caryl",
        "Fort Collins",
        "Thornton",
        "Northglenn"
    ],
    "Florida": [
        "Venice",
        "Bartow",
        "Edgewater",
        "Allapattah",
        "Hollywood",
        "Richmond West",
        "Pinecrest",
        "Homestead",
        "Meadow Woods",
        "West Little River",
        "Country Club",
        "Winter Springs",
        "Dunedin",
        "Palm Valley",
        "Naples",
        "Casselberry",
        "South Bradenton",
        "Palm Coast",
        "Merritt Island",
        "Altamonte Springs",
        "DeBary",
        "Poinciana",
        "Navarre",
        "Royal Palm Beach",
        "The Crossings",
        "Tamarac",
        "Fort Lauderdale",
        "Carol City",
        "Lake Magdalene",
        "Titusville",
        "Dania Beach",
        "Brownsville",
        "Largo",
        "Jacksonville Beach",
        "Ocala",
        "Bonita Springs",
        "Tampa",
        "Bradenton",
        "New Smyrna Beach",
        "Pompano Beach",
        "Miami Gardens",
        "Lauderdale Lakes",
        "Golden Gate",
        "Tallahassee",
        "Buenaventura Lakes",
        "Brent",
        "Crestview",
        "Palmetto Bay",
        "Coconut Creek",
        "Saint Cloud",
        "Pinewood",
        "Ponte Vedra Beach",
        "Pinellas Park",
        "Maitland",
        "Fort Walton Beach",
        "Valrico",
        "Cocoa",
        "Opa-locka",
        "South Miami Heights",
        "Ormond Beach",
        "Pembroke Pines",
        "Lake Worth Corridor",
        "Cutler Bay",
        "Southchase",
        "Keystone",
        "Fruit Cove",
        "Lauderhill",
        "Vero Beach South",
        "Ensley",
        "Kissimmee",
        "Fountainebleau",
        "Seminole",
        "Town 'n' Country",
        "Ojus",
        "Kendale Lakes",
        "Three Lakes",
        "Plantation",
        "Holiday",
        "Wellington",
        "Egypt Lake-Leto",
        "Miami Beach",
        "Temple Terrace",
        "Apopka",
        "Immokalee",
        "Lehigh Acres",
        "Oakland Park",
        "Sunset",
        "Clermont",
        "Kendall",
        "North Lauderdale",
        "East Lake",
        "Riverview",
        "Rockledge",
        "Winter Haven",
        "Lakeside",
        "Greater Northdale",
        "Golden Glades",
        "Fort Myers",
        "Jupiter",
        "Norland",
        "Stuart",
        "Vero Beach",
        "East Pensacola Heights",
        "Delray Beach",
        "Key West",
        "Riviera Beach",
        "Spring Hill",
        "Boynton Beach",
        "Greenacres City",
        "Land O' Lakes",
        "Palm Beach Gardens",
        "Hallandale Beach",
        "Carrollwood",
        "West and East Lealman",
        "Winter Garden",
        "Eustis",
        "Wright",
        "Davie",
        "Punta Gorda",
        "Ferry Pass",
        "Lakeland",
        "Lake Butler",
        "Cantonment",
        "Alafaya",
        "Deerfield Beach",
        "Pace",
        "West Palm Beach",
        "Iona",
        "Country Walk",
        "Fort Pierce",
        "Citrus Park",
        "Bloomingdale",
        "Miramar",
        "Coral Gables",
        "Lake Worth",
        "Daytona Beach",
        "Flagami",
        "Coconut Grove",
        "Palm City",
        "North Fort Myers",
        "North Miami",
        "Oviedo",
        "Cutler",
        "Port Saint Lucie",
        "Orlando",
        "Carrollwood Village",
        "West Pensacola",
        "Cutler Ridge",
        "Haines City",
        "Cape Coral",
        "Miami Lakes",
        "Bellview",
        "Clearwater",
        "Plant City",
        "Myrtle Grove",
        "Wesley Chapel",
        "Punta Gorda Isles",
        "Boca Del Mar",
        "Pine Hills",
        "San Carlos Park",
        "Bayshore Gardens",
        "Westchase",
        "Lutz",
        "West Melbourne",
        "Sebastian",
        "East Lake-Orient Park",
        "Sunrise",
        "Melbourne",
        "Aventura",
        "Palm Bay",
        "Saint Petersburg",
        "Glenvar Heights",
        "Princeton",
        "Sun City Center",
        "Ives Estates",
        "Pensacola",
        "Safety Harbor",
        "Tamiami",
        "Coral Terrace",
        "North Miami Beach",
        "Winter Park",
        "Coral Springs",
        "Sanford",
        "Westchester",
        "Port Orange",
        "Tarpon Springs",
        "Hialeah",
        "Ruskin",
        "Jasmine Estates",
        "Florida Ridge",
        "Wekiwa Springs",
        "Cooper City",
        "Miami",
        "Deltona",
        "Margate",
        "Sarasota",
        "The Hammocks",
        "Belle Glade",
        "Panama City",
        "Port Charlotte",
        "DeLand",
        "Bayonet Point",
        "Lealman",
        "Doral",
        "Ocoee",
        "North Port",
        "Boca Raton",
        "Leisure City",
        "Hialeah Gardens",
        "Palm Harbor",
        "The Villages",
        "University",
        "Sunny Isles Beach",
        "Leesburg",
        "Weston",
        "Estero",
        "Lynn Haven"
    ],
    "Texas": [
        "Dallas",
        "Brownwood",
        "Harlingen",
        "Ennis",
        "Cloverleaf",
        "Farmers Branch",
        "Cedar Hill",
        "Eagle Pass",
        "Plainview",
        "Angleton",
        "Corpus Christi",
        "Bryan",
        "Harker Heights",
        "Colleyville",
        "Amarillo",
        "Coppell",
        "Channelview",
        "Fort Hood",
        "Euless",
        "Haltom City",
        "Edinburg",
        "Socorro Mission Number 1 Colonia",
        "Beaumont",
        "Aldine",
        "Balch Springs",
        "Flower Mound",
        "Alamo",
        "Alvin",
        "Atascocita",
        "Georgetown",
        "Denison",
        "Del Rio",
        "Alice",
        "Corinth",
        "Groves",
        "Garland",
        "Big Spring",
        "Cedar Park",
        "Friendswood",
        "Pampa",
        "Gainesville",
        "West Odessa",
        "Socorro",
        "Odessa",
        "Burleson",
        "San Angelo",
        "El Paso",
        "Copperas Cove",
        "Brushy Creek",
        "Abilene",
        "Bellaire",
        "Donna",
        "Gatesville",
        "Corsicana",
        "Houston",
        "College Station",
        "DeSoto",
        "Cinco Ranch",
        "Grand Prairie",
        "Horizon City",
        "Benbrook",
        "Galveston",
        "Converse",
        "Grapevine",
        "Cleburne",
        "Conroe",
        "Hurst",
        "Lubbock",
        "Cibolo",
        "Highland Village",
        "Allen",
        "Frisco",
        "Brenham",
        "Fort Worth",
        "Humble",
        "Baytown",
        "Canyon Lake",
        "Greenville",
        "Fresno",
        "Midland",
        "Hereford",
        "Denton",
        "Duncanville"
    ],
    "Arkansas": [
        "Benton",
        "Pine Bluff",
        "Bentonville",
        "Forrest City",
        "El Dorado",
        "Texarkana",
        "Russellville",
        "Paragould",
        "Bella Vista",
        "Jonesboro",
        "North Little Rock",
        "Conway",
        "Little Rock",
        "Cabot",
        "Searcy",
        "Van Buren",
        "Jacksonville",
        "Rogers",
        "Hot Springs National Park",
        "Springdale",
        "Bryant",
        "Maumelle",
        "Fort Smith",
        "Blytheville",
        "Siloam Springs",
        "Hot Springs",
        "West Memphis"
    ],
    "Arizona": [
        "Lake Havasu City",
        "Queen Creek",
        "San Luis",
        "Apache Junction",
        "Surprise",
        "Scottsdale",
        "Casas Adobes",
        "Rio Rico",
        "Payson",
        "Sun City West",
        "Yuma",
        "Flowing Wells",
        "Fortuna Foothills",
        "Chandler",
        "Eloy",
        "Tucson",
        "Casa Grande",
        "Tempe",
        "Nogales",
        "Catalina Foothills",
        "Phoenix",
        "Douglas",
        "Sahuarita",
        "Bullhead City",
        "Drexel Heights",
        "Fountain Hills",
        "Anthem",
        "Tempe Junction",
        "El Mirage",
        "Sierra Vista",
        "Flagstaff",
        "Peoria",
        "Maricopa",
        "Prescott Valley",
        "Mesa",
        "Avondale",
        "Oro Valley",
        "Gilbert",
        "Green Valley",
        "Goodyear",
        "San Tan Valley",
        "Kingman",
        "Tanque Verde",
        "Sun City",
        "Prescott",
        "Buckeye",
        "Marana"
    ],
    "Tennessee": [
        "New South Memphis",
        "Tullahoma",
        "Lavergne",
        "Maryville",
        "Lebanon",
        "Murfreesboro",
        "East Brainerd",
        "Nashville",
        "Hendersonville",
        "Kingsport",
        "Chattanooga",
        "Mount Juliet",
        "Knoxville",
        "East Chattanooga",
        "Goodlettsville",
        "Greeneville",
        "Johnson City",
        "Collierville",
        "Gallatin",
        "Germantown",
        "Farragut",
        "Dyersburg",
        "East Ridge",
        "Brentwood Estates",
        "Cookeville",
        "Memphis",
        "Oak Ridge"
    ],
    "South Carolina": [
        "North Augusta",
        "Goose Creek",
        "Greer",
        "Summerville",
        "Seven Oaks",
        "Taylors",
        "Socastee",
        "North Charleston",
        "Myrtle Beach",
        "Hilton Head Island",
        "Simpsonville",
        "Anderson",
        "Greenwood",
        "Wade Hampton",
        "Easley",
        "Aiken",
        "Hanahan",
        "Saint Andrews",
        "Mauldin",
        "Spartanburg",
        "Charleston",
        "Rock Hill",
        "Sumter"
    ],
    "Massachusetts": [
        "Methuen",
        "Natick",
        "Shrewsbury",
        "Brockton",
        "Rockland",
        "Yarmouth",
        "Westfield",
        "South Peabody",
        "Everett",
        "Taunton",
        "Swansea",
        "Melrose",
        "Sudbury",
        "South Hadley",
        "Agawam",
        "Jamaica Plain",
        "Billerica",
        "Amesbury",
        "Wellesley",
        "Worcester",
        "Ludlow",
        "Acton",
        "Haverhill",
        "East Longmeadow",
        "Dedham",
        "Palmer",
        "Easthampton",
        "Framingham Center",
        "Beverly Cove",
        "Easton",
        "Belmont",
        "Fall River",
        "Norton",
        "Stoneham",
        "Longmeadow",
        "Lawrence",
        "Framingham",
        "Chelmsford",
        "Lynn",
        "Auburn",
        "Grafton",
        "Springfield",
        "New Bedford",
        "Wakefield",
        "Gloucester",
        "Leominster",
        "West Springfield",
        "Newburyport",
        "Chicopee",
        "Milton",
        "Danvers",
        "Winthrop",
        "Southbridge",
        "Saugus",
        "Attleboro",
        "Milford",
        "Franklin",
        "Reading",
        "Marblehead",
        "Boston",
        "South Boston",
        "Waltham",
        "Amherst Center",
        "Holden",
        "Westford",
        "Ashland",
        "North Chicopee",
        "Barnstable",
        "Northampton",
        "Randolph",
        "Malden",
        "Quincy",
        "Lowell",
        "Hanover",
        "Somerville",
        "Braintree",
        "Woburn",
        "Weymouth",
        "Dracut",
        "Brookline",
        "Chelsea",
        "Peabody",
        "Stoughton",
        "Marlborough",
        "Fairhaven",
        "Pittsfield",
        "Cambridge",
        "Watertown",
        "Holyoke",
        "Needham",
        "Tewksbury",
        "Abington",
        "Beverly"
    ],
    "Washington": [
        "University Place",
        "Parkland",
        "Aberdeen",
        "Lynnwood",
        "Monroe",
        "Mill Creek",
        "Bothell",
        "Mukilteo",
        "Bremerton",
        "Covington",
        "Orchards",
        "Cottage Lake",
        "Shoreline",
        "Mercer Island",
        "Lake Stevens",
        "North Creek",
        "Longview",
        "Five Corners",
        "West Lake Stevens",
        "Kennewick",
        "Bryn Mawr-Skyway",
        "Lacey",
        "Ellensburg",
        "Spokane Valley",
        "Silverdale",
        "Salmon Creek",
        "City of Sammamish",
        "Centralia",
        "Edmonds",
        "East Hill-Meridian",
        "Kent",
        "Frederickson",
        "Sammamish",
        "South Hill",
        "Pasco",
        "Yakima",
        "SeaTac",
        "Opportunity",
        "Camas",
        "Martha Lake",
        "Hazel Dell",
        "Moses Lake",
        "Issaquah",
        "Maple Valley",
        "Silver Firs",
        "Bonney Lake",
        "Pullman",
        "Tacoma",
        "Sunnyside",
        "Olympia",
        "Walla Walla",
        "Burien",
        "Lakewood",
        "Oak Harbor",
        "Puyallup",
        "Arlington",
        "Renton",
        "Redmond",
        "Richland",
        "Bainbridge Island",
        "Battle Ground",
        "Port Angeles",
        "Tumwater",
        "Vancouver",
        "Union Hill-Novelty Hill",
        "Bellingham",
        "Inglewood-Finn Hill",
        "Wenatchee",
        "Spokane",
        "Marysville",
        "Tukwila",
        "Seattle",
        "Spanaway",
        "Kenmore",
        "Fairwood",
        "Graham",
        "Mountlake Terrace",
        "Anacortes",
        "Federal Way",
        "West Lake Sammamish",
        "Kirkland"
    ],
    "Indiana": [
        "Muncie",
        "Carmel",
        "Vincennes",
        "Mishawaka",
        "Clarksville",
        "Crown Point",
        "Hobart",
        "Valparaiso",
        "Evansville",
        "Fishers",
        "LaPorte",
        "South Bend",
        "Griffith",
        "Crawfordsville",
        "Shelbyville",
        "Brownsburg",
        "West Lafayette",
        "Schererville",
        "East Chicago",
        "Munster",
        "Jasper",
        "New Albany",
        "Noblesville",
        "Fairfield Heights",
        "Kokomo",
        "Portage",
        "Fort Wayne",
        "Broad Ripple",
        "Terre Haute",
        "Highland",
        "Bloomington",
        "Seymour",
        "Logansport",
        "Gary",
        "Elkhart",
        "Granger",
        "Michigan City",
        "Hammond",
        "Indianapolis",
        "Merrillville",
        "Goshen",
        "Dyer",
        "Jeffersonville"
    ],
    "Wisconsin": [
        "North La Crosse",
        "Racine",
        "Stevens Point",
        "De Pere",
        "Kenosha",
        "Menomonee Falls",
        "Menasha",
        "Wausau",
        "Waukesha",
        "New Berlin",
        "Mequon",
        "Sun Prairie",
        "La Crosse",
        "Onalaska",
        "Fond du Lac",
        "West Bend",
        "Ashwaubenon",
        "Eau Claire",
        "Fitchburg",
        "Sheboygan",
        "Appleton",
        "Cudahy",
        "Oshkosh",
        "Caledonia",
        "Janesville",
        "Milwaukee",
        "Wisconsin Rapids",
        "Manitowoc",
        "Howard",
        "Greenfield",
        "Pleasant Prairie",
        "Kaukauna",
        "Beloit",
        "Neenah",
        "Marshfield",
        "Oconomowoc",
        "Muskego",
        "Middleton",
        "Brookfield",
        "South Milwaukee",
        "Beaver Dam",
        "Menomonie",
        "Wauwatosa",
        "Oak Creek",
        "Superior",
        "Green Bay",
        "West Allis"
    ],
    "Ohio": [
        "Fairview Park",
        "Troy",
        "East Cleveland",
        "Newark",
        "Xenia",
        "North Olmsted",
        "Huber Heights",
        "Bay Village",
        "Cincinnati",
        "North Royalton",
        "Vandalia",
        "Avon Center",
        "Maple Heights",
        "Defiance",
        "Grove City",
        "Marion",
        "Wooster",
        "Findlay",
        "Willoughby",
        "South Euclid",
        "Lancaster",
        "Gahanna",
        "Riverside",
        "Rocky River",
        "Akron",
        "Broadview Heights",
        "Green",
        "Aurora",
        "Eastlake",
        "Strongsville",
        "Tiffin",
        "Perrysburg",
        "Avon",
        "Sandusky",
        "New Philadelphia",
        "Beavercreek",
        "Norwood",
        "Twinsburg",
        "Massillon",
        "Westlake",
        "Pickerington",
        "Dayton",
        "Sidney",
        "Upper Arlington",
        "North Ridgeville",
        "Hudson",
        "Delaware",
        "Zanesville",
        "Piqua",
        "Steubenville",
        "Painesville",
        "Ashtabula",
        "Parma Heights",
        "Mentor",
        "Westerville",
        "Bowling Green",
        "Streetsboro",
        "Kettering",
        "Tallmadge",
        "Alliance",
        "Warren",
        "Hamilton",
        "Miamisburg",
        "Oregon",
        "Fairborn",
        "Medina",
        "Austintown",
        "Parma",
        "Wadsworth",
        "Mansfield",
        "Reynoldsburg",
        "Toledo",
        "Lima",
        "Mayfield Heights",
        "Barberton",
        "Boardman",
        "Trotwood",
        "Garfield Heights",
        "Whitehall",
        "Avon Lake",
        "Berea",
        "Sylvania",
        "Lorain",
        "Stow",
        "Elyria",
        "Mason",
        "North Canton",
        "Hilliard",
        "Solon",
        "Cuyahoga Falls",
        "Shaker Heights",
        "Fairfield",
        "Middleburg Heights",
        "Youngstown",
        "Brook Park",
        "Cleveland",
        "Euclid",
        "Niles",
        "Springboro"
    ],
    "Missouri": [
        "Wentzville",
        "Fort Leonard Wood",
        "Clayton",
        "Chesterfield",
        "Spanish Lake",
        "Warrensburg",
        "Webster Groves",
        "Ferguson",
        "Belton",
        "East Independence",
        "Cape Girardeau",
        "Raymore",
        "Maryland Heights",
        "Hannibal",
        "Affton",
        "Ballwin",
        "Saint Charles",
        "Liberty",
        "Sikeston",
        "Mehlville",
        "Kirksville",
        "Jefferson City",
        "St. Louis",
        "Wildwood",
        "Oakville",
        "Raytown",
        "University City",
        "Hazelwood",
        "Lemay",
        "Ozark",
        "Gladstone",
        "Grandview",
        "Overland",
        "Kirkwood",
        "Saint Joseph",
        "Blue Springs",
        "Creve Coeur",
        "Concord",
        "Arnold",
        "Sedalia",
        "Lee's Summit",
        "Nixa",
        "Rolla",
        "Saint Peters",
        "Florissant",
        "Joplin",
        "Poplar Bluff"
    ],
    "New Jersey": [
        "Livingston",
        "Pennsauken",
        "West New York",
        "Maplewood",
        "Montclair",
        "Somerset",
        "Toms River",
        "Colonia",
        "Rahway",
        "Madison",
        "Parsippany",
        "Ridgewood",
        "Point Pleasant",
        "Bridgewater",
        "Marlboro",
        "Willingboro",
        "Cliffside Park",
        "Edison",
        "Summit",
        "Ewing",
        "Paterson",
        "Jersey City",
        "New Milford",
        "Nutley",
        "Tinton Falls",
        "Hoboken",
        "Mahwah",
        "Piscataway",
        "West Orange",
        "South Vineland",
        "Sicklerville",
        "Union City",
        "Bloomfield",
        "Old Bridge",
        "Hopatcong Hills",
        "Irvington",
        "Iselin",
        "Asbury Park",
        "Hopatcong",
        "Clifton",
        "Kearny",
        "Woodbridge",
        "Warren Township",
        "North Bergen",
        "West Milford",
        "Bridgeton",
        "Atlantic City",
        "Secaucus",
        "Cranford",
        "Orange",
        "Cherry Hill",
        "Teaneck",
        "Englewood",
        "Bayonne",
        "Union",
        "Perth Amboy",
        "Hackensack",
        "Garfield",
        "Hillside",
        "Lodi",
        "New Brunswick",
        "Maple Shade",
        "Glassboro",
        "Fords",
        "Pleasantville",
        "Carteret",
        "Paramus",
        "Passaic",
        "Fair Lawn",
        "South Plainfield",
        "East Orange",
        "South Orange",
        "Linden",
        "Palisades Park",
        "Lindenwold",
        "Wayne",
        "Sayreville Junction",
        "Camden",
        "North Arlington",
        "Sayreville",
        "Wyckoff",
        "Mount Laurel",
        "Morristown",
        "Rutherford",
        "Bergenfield",
        "South River",
        "Vineland",
        "Scotch Plains",
        "Millville",
        "Avenel",
        "Dumont",
        "Long Branch",
        "Fort Lee",
        "South Old Bridge",
        "Williamstown",
        "Elizabeth",
        "Lyndhurst",
        "Ocean Acres",
        "East Brunswick",
        "North Plainfield"
    ],
    "Louisiana": [
        "New Iberia",
        "Marrero",
        "Prairieville",
        "Lafayette",
        "Natchitoches",
        "Chalmette",
        "Gretna",
        "Shenandoah",
        "Ruston",
        "Terrytown",
        "Bossier City",
        "Opelousas",
        "Metairie Terrace",
        "Baton Rouge",
        "Estelle",
        "Central",
        "Bayou Cane",
        "Metairie",
        "Harvey",
        "Lake Charles",
        "Shreveport",
        "New Orleans",
        "Kenner",
        "Sulphur",
        "Alexandria",
        "Slidell",
        "Houma",
        "Laplace"
    ],
    "North Carolina": [
        "Greensboro",
        "Cornelius",
        "Durham",
        "Kinston",
        "Kernersville",
        "Holly Springs",
        "Carrboro",
        "Indian Trail",
        "Rocky Mount",
        "Matthews",
        "Garner",
        "Mooresville",
        "Henderson",
        "Raleigh",
        "Albemarle",
        "Gastonia",
        "Wake Forest",
        "Goldsboro",
        "High Point",
        "West Raleigh",
        "Fuquay-Varina",
        "Fort Bragg",
        "Hope Mills",
        "Lumberton",
        "Thomasville",
        "Morrisville",
        "Mint Hill",
        "New Bern",
        "Charlotte",
        "Eden",
        "Huntersville",
        "Clemmons",
        "Boone",
        "Roanoke Rapids",
        "Statesville",
        "Asheboro",
        "Wilson",
        "Morganton",
        "Asheville",
        "Apex",
        "Elizabeth City",
        "Lenoir",
        "Hickory",
        "Kannapolis",
        "Havelock",
        "Wilmington",
        "Laurinburg",
        "Chapel Hill",
        "Winston-Salem"
    ],
    "Kansas": [
        "Emporia",
        "Topeka",
        "Lenexa",
        "Hays",
        "Gardner",
        "Junction City",
        "Prairie Village",
        "Derby",
        "Dodge City",
        "Great Bend",
        "Liberal",
        "Hutchinson",
        "Olathe",
        "Salina",
        "Newton",
        "Leavenworth",
        "Overland Park",
        "Kansas City",
        "Leawood",
        "Wichita",
        "Pittsburg"
    ],
    "West Virginia": [
        "Wheeling",
        "Weirton",
        "Weirton Heights"
    ],
    "Connecticut": [
        "Irving",
        "Branford",
        "West Torrington",
        "West Haven",
        "Wethersfield",
        "Ansonia",
        "City of Milford (balance)",
        "Wolcott",
        "Willimantic",
        "Windham",
        "Westport",
        "Cheshire",
        "Bridgeport",
        "Wallingford Center",
        "West Hartford",
        "Wilton"
    ],
    "Alabama": [
        "Prattville",
        "Homewood",
        "Center Point",
        "Trussville",
        "Talladega",
        "Florence",
        "Montgomery",
        "Dothan",
        "Dixiana",
        "Vestavia Hills",
        "Mountain Brook",
        "Gadsden",
        "Pelham",
        "Birmingham",
        "Huntsville",
        "Bessemer",
        "Prichard",
        "Tuscaloosa",
        "Phenix City",
        "Opelika",
        "Hueytown",
        "Northport",
        "Fairhope",
        "Tillmans Corner",
        "Mobile",
        "East Florence",
        "Daphne",
        "Hoover"
    ],
    "Oregon": [
        "Aloha",
        "Oak Grove",
        "Lake Oswego",
        "Grants Pass",
        "Woodburn",
        "Four Corners",
        "McMinnville",
        "Tigard",
        "Troutdale",
        "Hillsboro",
        "Tualatin",
        "Newberg",
        "Coos Bay",
        "Gresham",
        "Milwaukie",
        "Roseburg",
        "Altamont",
        "Central Point",
        "Hermiston",
        "Klamath Falls",
        "Sherwood",
        "Wilsonville",
        "Canby",
        "Corvallis",
        "Medford",
        "Salem",
        "Forest Grove",
        "Eugene",
        "Lents",
        "Oregon City",
        "Hayesville",
        "Portland",
        "Pendleton",
        "Bend",
        "West Linn",
        "Keizer"
    ],
    "Georgia": [
        "Dunwoody",
        "Carrollton",
        "Wilmington Island",
        "Americus",
        "Augusta",
        "Acworth",
        "Lithia Springs",
        "Milledgeville",
        "Columbus",
        "Calhoun",
        "Newnan",
        "St. Marys",
        "Hinesville",
        "Douglasville",
        "Statesboro",
        "Roswell",
        "Fayetteville",
        "McDonough",
        "Macon",
        "Smyrna",
        "Dalton",
        "Sandy Springs",
        "Snellville",
        "Evans",
        "Candler-McAfee",
        "Marietta",
        "Brookhaven",
        "Tifton",
        "Lawrenceville",
        "Alpharetta",
        "Atlanta",
        "Savannah",
        "East Point",
        "North Decatur",
        "Decatur",
        "Athens",
        "Pooler",
        "Kingsland",
        "Sugar Hill",
        "Canton",
        "Griffin",
        "Kennesaw",
        "Peachtree City",
        "Conyers",
        "Belvedere Park",
        "Rome",
        "Valdosta",
        "Stockbridge",
        "Warner Robins",
        "Tucker",
        "Redan",
        "Johns Creek",
        "Suwanee",
        "Forest Park",
        "Cartersville",
        "Brunswick",
        "Mableton",
        "Riverdale",
        "North Druid Hills"
    ],
    "North Dakota": [
        "Grand Forks",
        "Minot",
        "Fargo",
        "West Fargo",
        "Dickinson",
        "Bismarck",
        "Mandan"
    ],
    "Iowa": [
        "Cedar Falls",
        "Marshalltown",
        "Council Bluffs",
        "Cedar Rapids",
        "Waterloo",
        "West Des Moines",
        "Iowa City",
        "Ankeny",
        "Urbandale",
        "Muscatine",
        "Fort Dodge",
        "Mason City",
        "Ames",
        "Clive",
        "Coralville",
        "Bettendorf",
        "Des Moines",
        "Dubuque",
        "Johnston",
        "Sioux City",
        "Davenport",
        "Ottumwa"
    ],
    "Pennsylvania": [
        "Hazleton",
        "Chester",
        "State College",
        "Upper Saint Clair",
        "Murrysville",
        "Radnor",
        "Limerick",
        "West Chester",
        "Chambersburg",
        "Norristown",
        "Scranton",
        "New Castle",
        "Harrisburg",
        "Whitehall Township",
        "Cranberry Township",
        "McKeesport",
        "Johnstown",
        "King of Prussia",
        "Lansdale",
        "Pottstown",
        "Altoona",
        "Mountain Top",
        "Allentown",
        "Drexel Hill",
        "Philadelphia",
        "Phoenixville",
        "Williamsport",
        "Monroeville",
        "Wilkes-Barre",
        "Back Mountain",
        "Pittsburgh",
        "Plum",
        "Allison Park",
        "Carlisle",
        "Willow Grove",
        "Bethlehem",
        "Penn Hills",
        "York",
        "Bethel Park",
        "Wilkinsburg",
        "West Mifflin",
        "Mount Lebanon",
        "Hermitage"
    ],
    "Michigan": [
        "Burton",
        "Ferndale",
        "Southfield",
        "Eastpointe",
        "Lincoln Park",
        "Dearborn Heights",
        "Detroit",
        "Flint",
        "Sterling Heights",
        "Madison Heights",
        "Owosso",
        "Jackson",
        "Battle Creek",
        "West Bloomfield Township",
        "Hamtramck",
        "Ypsilanti",
        "Rochester Hills",
        "Redford",
        "Livonia",
        "Bay City",
        "Taylor",
        "Hazel Park",
        "Grandville",
        "Jenison",
        "Mount Clemens",
        "Saint Clair Shores",
        "Westland",
        "Novi",
        "Waverly",
        "Saginaw",
        "Farmington Hills",
        "Mount Pleasant",
        "Okemos",
        "Kentwood",
        "Holland",
        "Holt",
        "Shelby",
        "Haslett",
        "Iron River",
        "Muskegon",
        "Wyandotte",
        "Oak Park",
        "East Lansing",
        "Wyoming",
        "Grand Rapids",
        "Adrian",
        "Romulus",
        "Forest Hills",
        "Grosse Pointe Woods",
        "Waterford",
        "Trenton",
        "Pontiac",
        "Norton Shores",
        "Ann Arbor",
        "Allendale",
        "Lansing",
        "Marquette",
        "Southgate",
        "Port Huron",
        "Kalamazoo",
        "Dearborn",
        "Allen Park",
        "Auburn Hills",
        "Walker",
        "Royal Oak"
    ],
    "Rhode Island": [
        "West Warwick",
        "North Kingstown",
        "Warwick",
        "Newport",
        "Cranston",
        "Providence",
        "Westerly",
        "Bristol",
        "North Providence",
        "Central Falls",
        "Middletown",
        "Smithfield",
        "Coventry",
        "Woonsocket",
        "Pawtucket",
        "Barrington",
        "East Providence"
    ],
    "Utah": [
        "Centerville",
        "American Fork",
        "Millcreek",
        "Magna",
        "Herriman",
        "Logan",
        "Orem",
        "Salt Lake City",
        "West Valley City",
        "Kaysville",
        "South Jordan Heights",
        "East Millcreek",
        "North Salt Lake",
        "South Salt Lake",
        "Lehi",
        "Sandy Hills",
        "West Jordan",
        "South Ogden",
        "Brigham City",
        "Midvale",
        "Saint George",
        "Roy",
        "Clearfield",
        "Farmington",
        "Sandy City",
        "Holladay",
        "Cottonwood Heights",
        "Springville",
        "Ogden",
        "North Ogden",
        "Layton",
        "Taylorsville",
        "Draper",
        "Eagle Mountain",
        "Spanish Fork",
        "Provo",
        "Pleasant Grove",
        "South Jordan",
        "Cedar City",
        "Kearns",
        "Riverton",
        "Bountiful",
        "Tooele"
    ],
    "Maine": [
        "South Portland",
        "Bangor",
        "South Portland Gardens",
        "Lewiston",
        "Westbrook",
        "Waterville",
        "Saco",
        "West Scarborough",
        "Biddeford"
    ],
    "Hawaii": [
        "Kihei",
        "Waipahu",
        "Kaneohe",
        "Kahului",
        "Pearl City",
        "Mililani Town",
        "Honolulu",
        "Wahiawa",
        "Wailuku",
        "Kailua",
        "Schofield Barracks",
        "Makakilo City",
        "Hilo",
        "Ewa Gentry",
        "Makakilo"
    ],
    "New Mexico": [
        "South Valley",
        "Albuquerque",
        "Carlsbad",
        "Alamogordo",
        "Rio Rancho",
        "Santa Fe",
        "Las Cruces",
        "Gallup",
        "Enchanted Hills",
        "Hobbs"
    ],
    "Kentucky": [
        "Paducah",
        "Erlanger",
        "Winchester",
        "Hopkinsville",
        "Radcliff",
        "Newburg",
        "Frankfort",
        "Lexington-Fayette",
        "Richmond",
        "Shively",
        "Saint Matthews",
        "Jeffersontown",
        "Valley Station",
        "Pleasure Ridge Park",
        "Okolona",
        "Independence",
        "Murray",
        "Nicholasville",
        "Highview",
        "Burlington",
        "Meads",
        "Lexington",
        "Owensboro",
        "Ironville",
        "Elizabethtown",
        "Madisonville",
        "Fort Thomas",
        "Fern Creek"
    ],
    "Minnesota": [
        "Austin",
        "Lino Lakes",
        "Moorhead",
        "Columbia Heights",
        "Blaine",
        "Oakdale",
        "Chanhassen",
        "New Hope",
        "Woodbury",
        "Edina",
        "Chaska",
        "Fridley",
        "Albert Lea",
        "Lakeville",
        "Owatonna",
        "Red Wing",
        "Mankato",
        "Minnetonka Mills",
        "Ham Lake",
        "Shoreview",
        "Inver Grove Heights",
        "New Brighton",
        "Brooklyn Center",
        "Prior Lake",
        "Saint Paul",
        "Champlin",
        "Plymouth",
        "Sartell",
        "Saint Michael",
        "Anoka",
        "Willmar",
        "Coon Rapids",
        "Golden Valley",
        "Minneapolis",
        "Cottage Grove",
        "Maple Grove",
        "Hopkins",
        "Duluth",
        "West Saint Paul",
        "Crystal",
        "South Saint Paul",
        "Brooklyn Park",
        "Forest Lake",
        "Shakopee",
        "Hibbing",
        "White Bear Lake",
        "Faribault",
        "Saint Louis Park",
        "Richfield",
        "Winona",
        "Burnsville",
        "Buffalo",
        "Rosemount",
        "Minnetonka",
        "Apple Valley",
        "Elk River",
        "Andover",
        "Ramsey",
        "West Coon Rapids",
        "Northfield",
        "Eden Prairie",
        "Savage",
        "Eagan"
    ],
    "Nebraska": [
        "Norfolk",
        "Papillion",
        "North Platte",
        "Omaha",
        "Grand Island",
        "Hastings",
        "Lincoln",
        "Scottsbluff",
        "Bellevue",
        "Kearney",
        "La Vista"
    ],
    "Montana": [
        "Great Falls",
        "Kalispell",
        "Butte",
        "Helena",
        "Billings",
        "Butte-Silver Bow (Balance)",
        "Missoula",
        "Bozeman"
    ],
    "Alaska": [
        "Juneau",
        "Fairbanks",
        "Anchorage",
        "Eagle River",
        "Badger"
    ],
    "South Dakota": [
        "Rapid City",
        "Brookings",
        "Mitchell",
        "Sioux Falls"
    ],
    "Virginia": [
        "Fort Hunt",
        "Oak Hill"
    ],
    "New Hampshire": [
        "Nashua",
        "Bedford",
        "Laconia",
        "Merrimack",
        "Manchester",
        "Derry",
        "Derry Village",
        "East Concord",
        "Portsmouth",
        "Keene"
    ],
    "Wyoming": [
        "Gillette",
        "Rock Springs",
        "Cheyenne",
        "Laramie",
        "Casper",
        "Sheridan"
    ],
    "Vermont": [
        "South Burlington",
        "Colchester",
        "Rutland"
    ],
    "Delaware": [
        "Bear",
        "Dover"
    ],
    "District of Columbia": [
        "Washington, D.C."
    ]
}